package Cell;


/**
* Cell/Station.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Tuesday, May 2, 2023 4:45:28 PM MSK
*/


/* =B5@D59A 107>2>9 AB0=F88 */
public interface Station extends StationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Station
